parameters = [
  { name = "dev.frontend.catalogue_url", value = "http://catalogue.devtb.online:8080/", type = "String" },
  { name = "dev.frontend.user_url", value = "http://user.devtb.online:8080/", type = "String" },
  { name = "dev.frontend.cart_url", value = "http://cart.devtb.online:8080/", type = "String" },
  { name = "dev.frontend.shipping_url", value = "http://shipping.devtb.online:8080/", type = "String" },
  { name = "dev.frontend.payment_url", value = "http://payment.devtb.online:8080/", type = "String" },
  { name = "dev.cart.redis_host", value = "redis.devtb.online", type = "String" },
  { name = "dev.cart.catalogue_host", value = "catalogue.devtb.online", type = "String" },
  { name = "dev.cart.catalogue_port", value = "8080", type = "String" },
  { name = "dev.catalogue.mongo", value = "true", type = "String" },
  { name = "dev.catalogue.mongo_url", value = "mongodb://mongodb.devtb.online:27017/catalogue", type = "String" },
  { name = "dev.dispatch.amqp_host", value = "rabbitmq.devtb.online", type = "String" },
  { name = "dev.payment.cart_host", value = "cart.devtb.online", type = "String" },
  { name = "dev.payment.cart_port", value = "8080", type = "String" },
  { name = "dev.payment.user_host", value = "user.devtb.online", type = "String" },
  { name = "dev.payment.user_port", value = "8080", type = "String" },
  { name = "dev.payment.amqp_host", value = "rabbitmq.devtb.online", type = "String" },
  { name = "dev.shipping.cart_endpoint", value = "cart.devtb.online:8080", type = "String" },
  { name = "dev.shipping.db_host", value = "mysql.devtb.online", type = "String" },
  { name = "dev.user.mongo", value = "true", type = "String" },
  { name = "dev.user.redis_host", value = "redis.devtb.online", type = "String" },
  { name = "dev.user.mongo_url", value = "mongodb://mongodb.devtb.online:27017/users", type = "String" }
]